(function(){
'use strict';
const TARGET_CAL=2100,TARGET_PROTEIN=155;
const mealPlan=[
 {meal:'Breakfast',emoji:'🥣',name:'Protein oats bowl',items:'50g oats + 1 scoop whey + 200g Greek yogurt + berries',cal:450,protein:42},
 {meal:'Lunch',emoji:'🍛',name:'Indian protein lunch',items:'150g cooked rice + dal + 150g paneer/tofu + mixed vegetables + salad',cal:600,protein:43},
 {meal:'Snack',emoji:'🥛',name:'Protein snack',items:'1 scoop whey + 1 banana or apple',cal:250,protein:25},
 {meal:'Dinner',emoji:'🥗',name:'High-protein dinner',items:'2 rotis + 180g tofu/paneer + vegetables + 150g curd',cal:600,protein:42},
 {meal:'Flexible',emoji:'🍓',name:'Remaining calories',items:'Fruit / Greek yogurt / milk depending on the day',cal:200,protein:3}
];
const plans={
  1:{title:'Monday · Upper Body A',items:[['Chest Press','3 × 8–12','chest press proper form'],['Lat Pulldown','3 × 8–12','lat pulldown proper form'],['Seated Cable Row','3 × 8–12','seated cable row proper form'],['Shoulder Press','2 × 8–12','machine shoulder press proper form'],['Dumbbell Curl','2 × 10–12','dumbbell bicep curl proper form'],['Triceps Pushdown','2 × 10–15','tricep pushdown proper form']]},
  2:{title:'Tuesday · Lower Body A',items:[['Leg Press','3 × 8–12','leg press proper form'],['Romanian Deadlift','3 × 8–10','romanian deadlift proper form'],['Leg Curl','2 × 10–12','leg curl proper form'],['Leg Extension','2 × 10–12','leg extension proper form'],['Calf Raise','3 × 10–15','calf raise proper form'],['Dead Bug','3 × 8–12/side','dead bug exercise proper form']]},
  3:{title:'Wednesday · Recovery',items:[['Brisk Walk','20–30 min','brisk walking technique'],['Mobility','10 min','full body mobility routine beginner']]},
  4:{title:'Thursday · Upper Body B',items:[['Incline Dumbbell Press','3 × 8–12','incline dumbbell press proper form'],['Chest-Supported Row','3 × 8–12','chest supported row proper form'],['Lat Pulldown','3 × 8–12','lat pulldown proper form'],['Lateral Raise','3 × 10–15','dumbbell lateral raise proper form'],['Dumbbell Curl','2 × 10–12','dumbbell bicep curl proper form'],['Triceps Pushdown','2 × 10–15','tricep pushdown proper form']]},
  5:{title:'Friday · Lower Body B',items:[['Squat / Goblet Squat','3 × 8–12','goblet squat proper form'],['Romanian Deadlift','3 × 8–10','dumbbell romanian deadlift proper form'],['Bulgarian Split Squat','2 × 8–12/leg','bulgarian split squat proper form'],['Leg Curl','2 × 10–12','leg curl proper form'],['Calf Raise','3 × 10–15','calf raise proper form'],['Plank','3 × 30–60 sec','plank proper form']]},
  6:{title:'Saturday · Active Recovery',items:[['Walking','30–45 min','walking workout beginner'],['Core','10 min','beginner core workout']]},
  0:{title:'Sunday · Rest',items:[['Rest','Recovery day','active recovery stretching beginner']]}
};
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));}
function food(){const s=document.getElementById('food');if(!s)return;s.innerHTML='<div class="section-title"><h2>Today\'s food plan</h2><span class="muted">~2,100 kcal · 150–165g protein</span></div><div class="card"><div class="tip"><strong>🎯 Your target</strong><br>Build meals around protein, vegetables and sensible portions. If you eat outside or have biryani, upload the photo and use the estimate below.</div><div id="dailyMealPlan"></div></div><div class="card"><div class="section-title"><h2>📸 What did you actually eat?</h2><span class="muted">Photo estimate</span></div><div class="food-photo"><strong>Take a photo or choose one</strong><p class="muted">Upload your meal photo. The app will prepare an estimate you can adjust before saving.</p><input id="newFoodPhoto" type="file" accept="image/*" capture="environment"><img id="newFoodPreview" class="preview"></div><div id="photoEstimate" class="tip" style="display:none;margin-top:12px"></div><div class="form" style="margin-top:12px"><div class="field"><label>Estimated calories</label><input id="photoCalories" type="number" placeholder="e.g. 650"></div><div class="field"><label>Estimated protein (g)</label><input id="photoProtein" type="number" placeholder="e.g. 30"></div><div class="field full"><label>Food / portion notes</label><textarea id="photoNotes" rows="2" placeholder="e.g. chicken biryani, 1 full plate"></textarea></div></div><button class="btn save" id="savePhotoMeal">Save meal estimate</button><div id="newFoodMsg" class="message"></div></div><div class="card"><div class="section-title"><h2>Today\'s intake</h2><strong id="newFoodTotals">0 kcal · 0g protein</strong></div><div id="newFoodList"></div></div>';
 const list=document.getElementById('dailyMealPlan');list.innerHTML=mealPlan.map(m=>'<div class="meal-row"><div class="emoji">'+m.emoji+'</div><div style="flex:1"><strong>'+m.meal+' · '+m.name+'</strong><div class="muted">'+m.items+'</div><small class="muted">≈ '+m.cal+' kcal · '+m.protein+'g protein</small></div></div>').join('');
 document.getElementById('newFoodPhoto').onchange=function(){const f=this.files&&this.files[0];if(!f)return;const r=new FileReader();r.onload=function(){const p=document.getElementById('newFoodPreview');p.src=r.result;p.style.display='block';document.getElementById('photoEstimate').style.display='block';document.getElementById('photoEstimate').innerHTML='<strong>Photo received ✓</strong><br>For an accurate estimate, I need to identify the foods and portions. If this photo is uploaded in the ChatGPT conversation, I can analyse it and give you the calories and protein. For the app, enter or adjust the estimate below.'};r.readAsDataURL(f)};
 document.getElementById('savePhotoMeal').onclick=saveMeal;renderMeals();
}
function saveMeal(){const c=Number(document.getElementById('photoCalories').value||0),p=Number(document.getElementById('photoProtein').value||0),n=document.getElementById('photoNotes').value||'Meal photo';if(!c){document.getElementById('newFoodMsg').textContent='Add an estimated calorie value before saving.';return}let all={};try{all=JSON.parse(localStorage.getItem('fitnessAssistantFoodV2')||'{}')}catch(e){}all[new Date().toISOString().slice(0,10)]=all[new Date().toISOString().slice(0,10)]||[];all[new Date().toISOString().slice(0,10)].push({date:new Date().toISOString(),meal:'Photo meal',calories:c,protein:p,notes:n});localStorage.setItem('fitnessAssistantFoodV2',JSON.stringify(all));document.getElementById('newFoodMsg').textContent='Meal saved ✓';renderMeals()}
function renderMeals(){const key=new Date().toISOString().slice(0,10);let all={};try{all=JSON.parse(localStorage.getItem('fitnessAssistantFoodV2')||'{}')}catch(e){}const rows=all[key]||[];let c=0,p=0;const el=document.getElementById('newFoodList');if(!el)return;el.innerHTML=rows.map(x=>{c+=Number(x.calories||0);p+=Number(x.protein||0);return '<div class="meal-row"><div class="emoji">📷</div><div><strong>'+esc(x.meal||'Meal')+'</strong><div class="muted">'+esc(x.notes||'')+'</div><small class="muted">'+Number(x.calories||0)+' kcal · '+Number(x.protein||0)+'g protein</small></div></div>'}).join('')||'<div class="empty">No meals recorded yet.</div>';const t=document.getElementById('newFoodTotals');if(t)t.textContent=c+' kcal · '+p+'g protein';}
function workout(){const s=document.getElementById('workout');if(!s)return;const w=plans[new Date().getDay()];s.innerHTML='<div class="section-title"><h2>'+w.title+'</h2><span class="muted">4 training days + recovery</span></div><div class="card"><div class="tip">Warm up for 5–10 minutes. Choose a weight that leaves about 1–3 good reps in reserve. Rest 60–120 seconds between sets.</div><div id="newWorkoutList" style="margin-top:8px"></div><button class="btn save" id="newMarkWorkout">Mark today\'s workout complete ✓</button><div id="newWorkoutMsg" class="message"></div></div><div class="card"><strong>▶ Exercise technique</strong><p class="muted">Use the YouTube reference beside each movement before your first set.</p></div>';
 document.getElementById('newWorkoutList').innerHTML=w.items.map((x,i)=>'<div class="exercise"><div style="width:30px;font-weight:800">'+(i+1)+'</div><div style="flex:1"><strong>'+x[0]+'</strong><small>'+x[1]+'</small><a class="link" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query='+encodeURIComponent(x[2])+'">▶ YouTube reference</a></div></div>').join('');document.getElementById('newMarkWorkout').onclick=function(){let all={};try{all=JSON.parse(localStorage.getItem('fitnessAssistantDailyV2')||'{}')}catch(e){}const k=new Date().toISOString().slice(0,10);all[k]=all[k]||{date:k};all[k].workout=true;localStorage.setItem('fitnessAssistantDailyV2',JSON.stringify(all));document.getElementById('newWorkoutMsg').textContent='Workout completed today ✓'};
}
function init(){food();workout();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();